package org.albedu.oauth2;

public class Constant {
	public static final String SAVED_INPUT_DATA_FILE_PATH = "config/saved-data.props";
	public static final String APP_PROPERTIES_FILE_PATH = "config/app-properties.props";
	public static final String LOG4J_UI_TOOL_CONFIG_FILE_PATH = "config/log4j-ui-tool.properties";
	public static final String KEY_APP_ICON_PATH = "APP_ICON_PATH";
	public static final String KEY_LABEL_FONT_SIZE = "LABEL_FONT_SIZE";
	public static final String KEY_BUTTON_FONT_SIZE = "BUTTON_FONT_SIZE";
	public static final String KEY_SPLIT_PANE_RESIZE_WEIGHT = "SPLIT_PANE_RESIZE_WEIGHT";
	public static final String KEY_LAST_EXIT_TIME = "LAST_EXIT_TIME";
	public static final String KEY_TIMER_OFFSET = "TIMER_OFFSET";
	public static final String KEY_REFRESH_TOKEN_PANEL_CLIENT_ID = "REFRESH_TOKEN_PANEL_CLIENT_ID";
	public static final String KEY_REFRESH_TOKEN_PANEL_CLIENT_SECRET = "REFRESH_TOKEN_PANEL_CLIENT_SECRET";
	public static final String KEY_REFRESH_TOKEN_PANEL_REFRESH_TOKEN = "REFRESH_TOKEN_PANEL_REFRESH_TOKEN";
	public static final String KEY_REFRESH_TOKEN_PANEL_ACCESS_TOKEN = "REFRESH_TOKEN_PANEL_ACCESS_TOKEN";
	public static final String KEY_REFRESH_TOKEN_PANEL_TIMER = "REFRESH_TOKEN_PANEL_TIMER";
	public static final String KEY_GEN_OAUTH2_STR_PANEL_USER = "GEN_OAUTH2_STR_PANEL_USER";
	public static final String KEY_GEN_OAUTH2_STR_PANEL_ACCESS_TOKEN = "GEN_OAUTH2_STR_PANEL_ACCESS_TOKEN";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_CLIENT_ID = "GEN_OAUTH2_TOKEN_PANEL_CLIENT_ID";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_CLIENT_SECRET = "GEN_OAUTH2_TOKEN_PANEL_CLIENT_SECRET";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_SCOPE = "GEN_OAUTH2_TOKEN_PANEL_SCOPE";
	// public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_VERIFICATION_CODE = "GEN_OAUTH2_TOKEN_PANEL_VERIFICATION_CODE";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_ACCESS_TOKEN = "GEN_OAUTH2_TOKEN_PANEL_ACCESS_TOKEN";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_REFRESH_TOKEN = "GEN_OAUTH2_TOKEN_PANEL_REFRESH_TOKEN";
	public static final String KEY_GEN_OAUTH2_TOKEN_PANEL_TIMER = "GEN_OAUTH2_TOKEN_PANEL_TIMER";
	public static final String KEY_TEST_IMAP_AUTH_PANEL_USER = "TEST_IMAP_AUTH_PANEL_USER";
	public static final String KEY_TEST_IMAP_AUTH_PANEL_ACCESS_TOKEN = "TEST_IMAP_AUTH_PANEL_ACCESS_TOKEN";
	public static final String KEY_TEST_SMTP_AUTH_PANEL_USER = "TEST_SMTP_AUTH_PANEL_USER";
	public static final String KEY_TEST_SMTP_AUTH_PANEL_ACCESS_TOKEN = "TEST_SMTP_AUTH_PANEL_ACCESS_TOKEN";
	public static final String KEY_BASE64_TO_TEXT_PANEL_BASE64_STR = "BASE64_TO_TEXT_PANEL_BASE64_STR";
	public static final String KEY_SETTINGS_PANEL_VERIFICATION_CODE_REDIRECT_URI = "SETTINGS_PANEL_VERIFICATION_CODE_REDIRECT_URI";
	public static final String KEY_URL_PARAM_QUERY_KEY_CODE = "URL_PARAM_QUERY_KEY_CODE";
	public static final String KEY_WEB_FILE_ROOT_DIR = "WEB_FILE_ROOT_DIR";
	public static final String KEY_NUMBER_OF_THREADS_IN_HTTP_THREAD_POOL = "NUMBER_OF_THREADS_IN_HTTP_THREAD_POOL";
	public static final String KEY_IS_MAC_OS = "IS_MAC_OS";
	public static final String KEY_MAC_OS_HOME_DIR_PROPERTY_NAME = "MAC_OS_HOME_DIR_PROPERTY_NAME";
}
